// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Zk5vZAfE6VNIGj1OIdR78SMnkUG7HM0',
    appId: '1:528029626394:web:fda3638daafa36675ae1a3',
    messagingSenderId: '528029626394',
    projectId: 'drive-89cf2',
    authDomain: 'drive-89cf2.firebaseapp.com',
    databaseURL: 'https://drive-89cf2-default-rtdb.firebaseio.com',
    storageBucket: 'drive-89cf2.firebasestorage.app',
    measurementId: 'G-599YD239D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7xzlnBAy49hGxUpaIczquMbHFsvnTp4k',
    appId: '1:528029626394:android:39961061ca7571515ae1a3',
    messagingSenderId: '528029626394',
    projectId: 'drive-89cf2',
    databaseURL: 'https://drive-89cf2-default-rtdb.firebaseio.com',
    storageBucket: 'drive-89cf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE6cxuwJzS086jad2KFM2CTiCfLCDHiWU',
    appId: '1:528029626394:ios:ffc57abf7077e8bc5ae1a3',
    messagingSenderId: '528029626394',
    projectId: 'drive-89cf2',
    databaseURL: 'https://drive-89cf2-default-rtdb.firebaseio.com',
    storageBucket: 'drive-89cf2.firebasestorage.app',
    iosBundleId: 'com.example.driver',
  );
}
